# Generated by Django 5.0.7 on 2024-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_alter_user_date_joined_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
